---
abstract: 'A storage class for Catalyst Authentication using L<Fey::ORM>'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Store-Fey-ORM
requires:
  Catalyst::Authentication::User: 0
  Class::Accessor::Fast: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/keedi/Catalyst-Authentication-Store-Fey-ORM.git
version: 0.001
